<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<div id="page-home">
    	
	<?php foreach ($productList as $product): ?>
	
		<article>
			<h3><?= $product['name'] ?></h3>
			<p><?= $product['description'] ?></p>
			<p><?= Tools::getPrettyPrice($product['priceHT']) ?></p>
			<img src="<?= $wwwUrl ?>/images/meals/<?=  $product['image'] ?>">
		</article>

	<?php endforeach ?>
	
	<div style="clear:both"></div>
</div>