<h2>Commande</h2>

<div class="box-add-article">
	<label>
		Produits
		<select>
			<?php foreach ($productList as $product): ?>
				<option value="<?= $product['id'] ?>"><?= $product['name']?></option>
			<?php endforeach ?>
		</select>
	</label>

	<div class="product-info">
	</div>

	<label>quantité<input type="number" id="quantity"></label>
	<button type="button" id="btn-add">ajouter</button>
</div>


<div class="box-cart">
</div>

<form method="post" action="<?= $requestUrl ?>/validation">
	<button type="submit">Valider la commande</button>
</form>

<a href="<?= $requestUrl ?>">Annuler</a>


<script src="<?= $wwwUrl ?>/js/order.js"></script>